package main

var (
	Insn_x86_64     map[string]string
	Cond_x86_64     map[string]string
	CondInsn_x86_64 []string
)

func init() {
	Insn_x86_64 = map[string]string{
		"aaa":             "ASCII Adjust After Addition",
		"aad":             "ASCII Adjust AX Before Division",
		"aam":             "ASCII Adjust AX After Multiply",
		"aas":             "ASCII Adjust AL After Subtraction",
		"adc":             "Add with Carry",
		"adcx":            "Unsigned Integer Addition of Two Operands with Carry Flag",
		"add":             "Add",
		"addpd":           "Add Packed Double-Precision Floating-Point Values",
		"addps":           "Add Packed Single-Precision Floating-Point Values",
		"addsd":           "Add Scalar Double-Precision Floating-Point Values",
		"addss":           "Add Scalar Single-Precision Floating-Point Values",
		"addsubpd":        "Packed Double-FP Add/Subtract",
		"addsubps":        "Packed Single-FP Add/Subtract",
		"adox":            "Unsigned Integer Addition of Two Operands with Overflow Flag",
		"aesdec":          "Perform One Round of an AES Decryption Flow",
		"aesdeclast":      "Perform Last Round of an AES Decryption Flow",
		"aesenc":          "Perform One Round of an AES Encryption Flow",
		"aesenclast":      "Perform Last Round of an AES Encryption Flow",
		"aesimc":          "Perform the AES InvMixColumn Transformation",
		"aeskeygenassist": "AES Round Key Generation Assist",
		"and":             "Logical AND",
		"andn":            "Logical AND NOT",
		"andnpd":          "Bitwise Logical AND NOT of Packed Double-Precision Floating-Point Values",
		"andnps":          "Bitwise Logical AND NOT of Packed Single-Precision Floating-Point Values",
		"andpd":           "Bitwise Logical AND of Packed Double-Precision Floating-Point Values",
		"andps":           "Bitwise Logical AND of Packed Single-Precision Floating-Point Values",
		"arpl":            "Adjust RPL Field of Segment Selector",
		"bextr":           "Bit Field Extract",
		"blendpd":         "Blend Packed Double Precision Floating-Point Values",
		"blendps":         "Blend Packed Single Precision Floating-Point Values",
		"blendvpd":        "Variable Blend Packed Double Precision Floating-Point Values",
		"blendvps":        "Variable Blend Packed Single Precision Floating-Point Values",
		"blsi":            "Extract Lowest Set Isolated Bit",
		"blsmsk":          "Get Mask Up to Lowest Set Bit",
		"blsr":            "Reset Lowest Set Bit",
		"bound":           "Check Array Index Against Bounds",
		"bsf":             "Bit Scan Forward",
		"bsr":             "Bit Scan Reverse",
		"bswap":           "Byte Swap",
		"bt":              "Bit Test",
		"btc":             "Bit Test and Complement",
		"btr":             "Bit Test and Reset",
		"bts":             "Bit Test and Set",
		"bzhi":            "Zero High Bits Starting with Specified Bit Position",
		"call":            "Call Procedure",
		"cbw":             "Convert Byte to Word/Convert Word to Doubleword/Convert Doubleword to Quadword",
		"cdq":             "Convert Word to Doubleword/Convert Doubleword to Quadword",
		"cdqe":            "Convert Byte to Word/Convert Word to Doubleword/Convert Doubleword to Quadword",
		"clac":            "Clear AC Flag in EFLAGS Register",
		"clc":             "Clear Carry Flag",
		"cld":             "Clear Direction Flag",
		"clflush":         "Flush Cache Line",
		"cli":             "Clear Interrupt Flag",
		"clts":            "Clear Task-Switched Flag in CR0",
		"cmc":             "Complement Carry Flag",
		"cmov":            "Conditional Move",
		"cmp":             "Compare Two Operands",
		"cmppd":           "Compare Packed Double-Precision Floating-Point Values",
		"cmpps":           "Compare Packed Single-Precision Floating-Point Values",
		"cmps":            "Compare String Operands",
		"cmpsb":           "Compare String Operands",
		"cmpsd":           "Compare String Operands",
		"cmpsq":           "Compare String Operands",
		"cmpss":           "Compare Scalar Single-Precision Floating-Point Values",
		"cmpsw":           "Compare String Operands",
		"cmpxchg":         "Compare and Exchange",
		"cmpxchg16b":      "Compare and Exchange Bytes",
		"cmpxchg8b":       "Compare and Exchange Bytes",
		"comisd":          "Compare Scalar Ordered Double-Precision Floating-Point Values and Set EFLAGS",
		"comiss":          "Compare Scalar Ordered Single-Precision Floating-Point Values and Set EFLAGS",
		"cpuid":           "CPU Identification",
		"cqo":             "Convert Word to Doubleword/Convert Doubleword to Quadword",
		"crc32":           "Accumulate CRC32 Value",
		"cvtdq2pd":        "Convert Packed Dword Integers to Packed Double-Precision FP Values",
		"cvtdq2ps":        "Convert Packed Dword Integers to Packed Single-Precision FP Values",
		"cvtpd2dq":        "Convert Packed Double-Precision FP Values to Packed Dword Integers",
		"cvtpd2pi":        "Convert Packed Double-Precision FP Values to Packed Dword Integers",
		"cvtpd2ps":        "Convert Packed Double-Precision FP Values to Packed Single-Precision FP Values",
		"cvtpi2pd":        "Convert Packed Dword Integers to Packed Double-Precision FP Values",
		"cvtpi2ps":        "Convert Packed Dword Integers to Packed Single-Precision FP Values",
		"cvtps2dq":        "Convert Packed Single-Precision FP Values to Packed Dword Integers",
		"cvtps2pd":        "Convert Packed Single-Precision FP Values to Packed Double-Precision FP Values",
		"cvtps2pi":        "Convert Packed Single-Precision FP Values to Packed Dword Integers",
		"cvtsd2si":        "Convert Scalar Double-Precision FP Value to Integer",
		"cvtsd2ss":        "Convert Scalar Double-Precision FP Value to Scalar Single-Precision FP Value",
		"cvtsi2sd":        "Convert Dword Integer to Scalar Double-Precision FP Value",
		"cvtsi2ss":        "Convert Dword Integer to Scalar Single-Precision FP Value",
		"cvtss2sd":        "Convert Scalar Single-Precision FP Value to Scalar Double-Precision FP Value",
		"cvtss2si":        "Convert Scalar Single-Precision FP Value to Dword Integer",
		"cvttpd2dq":       "Convert with Truncation Packed Double-Precision FP Values to Packed Dword Integers",
		"cvttpd2pi":       "Convert with Truncation Packed Double-Precision FP Values to Packed Dword Integers",
		"cvttps2dq":       "Convert with Truncation Packed Single-Precision FP Values to Packed Dword Integers",
		"cvttps2pi":       "Convert with Truncation Packed Single-Precision FP Values to Packed Dword Integers",
		"cvttsd2si":       "Convert with Truncation Scalar Double-Precision FP Value to Signed Integer",
		"cvttss2si":       "Convert with Truncation Scalar Single-Precision FP Value to Dword Integer",
		"cwd":             "Convert Word to Doubleword/Convert Doubleword to Quadword",
		"cwde":            "Convert Byte to Word/Convert Word to Doubleword/Convert Doubleword to Quadword",
		"daa":             "Decimal Adjust AL after Addition",
		"das":             "Decimal Adjust AL after Subtraction",
		"dec":             "Decrement by 1",
		"div":             "Unsigned Divide",
		"divpd":           "Divide Packed Double-Precision Floating-Point Values",
		"divps":           "Divide Packed Single-Precision Floating-Point Values",
		"divsd":           "Divide Scalar Double-Precision Floating-Point Values",
		"divss":           "Divide Scalar Single-Precision Floating-Point Values",
		"dppd":            "Dot Product of Packed Double Precision Floating-Point Values",
		"dpps":            "Dot Product of Packed Single Precision Floating-Point Values",
		"emms":            "Empty MMX Technology State",
		"enter":           "Make Stack Frame for Procedure Parameters",
		"extractps":       "Extract Packed Single Precision Floating-Point Value",
		"f2xm1":           "Compute 2x–1",
		"fabs":            "Absolute Value",
		"fadd":            "Add",
		"faddp":           "Add and Pop",
		"fbld":            "Load Binary Coded Decimal",
		"fbstp":           "Store BCD Integer and Pop",
		"fchs":            "Change Sign",
		"fclex":           "Clear Exceptions",
		"fcmov":           "Floating-Point Conditional Move",
		"fcom":            "Compare Floating Point Values",
		"fcomi":           "Compare Floating Point Values and Set EFLAGS",
		"fcomip":          "Compare Floating Point Values and Set EFLAGS and Pop",
		"fcomp":           "Compare Floating Point Values and Pop",
		"fcompp":          "Compare Floating Point Values and Pop twice",
		"fcos":            "Cosine",
		"fdecstp":         "Decrement Stack-Top Pointer",
		"fdiv":            "Divide",
		"fdivp":           "Divide and Pop",
		"fdivr":           "Reverse Divide",
		"fdivrp":          "Reverse Divide and Pop",
		"ffree":           "Free Floating-Point Register",
		"fiadd":           "Add",
		"ficom":           "Compare Integer",
		"ficomp":          "Compare Integer and Pop",
		"fidiv":           "Divide",
		"fidivr":          "Reverse Divide",
		"fild":            "Load Integer",
		"fimul":           "Multiply",
		"fincstp":         "Increment Stack-Top Pointer",
		"finit":           "Initialize Floating-Point Unit",
		"fist":            "Store Integer",
		"fistp":           "Store Integer and Pop",
		"fisttp":          "Store Integer with Truncation",
		"fisub":           "Subtract",
		"fisubr":          "Reverse Subtract",
		"fld":             "Load Floating Point Value",
		"fld1":            "Load Constant (+1.0)",
		"fldcw":           "Load x87 FPU Control Word",
		"fldenv":          "Load x87 FPU Environment",
		"fldl2e":          "Load Constant (log_2(e))",
		"fldl2t":          "Load Constant (log_2(10))",
		"fldlg2":          "Load Constant (log_10(2))",
		"fldln2":          "Load Constant (log_e(2))",
		"fldpi":           "Load Constant (PI)",
		"fldz":            "Load Constant (+0.0)",
		"fmul":            "Multiply",
		"fmulp":           "Multiply and Pop",
		"fnclex":          "Clear Exceptions",
		"fninit":          "Initialize Floating-Point Unit",
		"fnop":            "No Operation",
		"fnsave":          "Store x87 FPU State",
		"fnstcw":          "Store x87 FPU Control Word",
		"fnstenv":         "Store x87 FPU Environment",
		"fnstsw":          "Store x87 FPU Status Word",
		"fpatan":          "Partial Arctangent",
		"fprem":           "Partial Remainder",
		"fprem1":          "Partial Remainder (IEEE)",
		"fptan":           "Partial Tangent",
		"frndint":         "Round to Integer",
		"frstor":          "Restore x87 FPU State",
		"fsave":           "Store x87 FPU State",
		"fscale":          "Scale",
		"fsin":            "Sine",
		"fsincos":         "Sine and Cosine",
		"fsqrt":           "Square Root",
		"fst":             "Store Floating Point Value",
		"fstcw":           "Store x87 FPU Control Word",
		"fstenv":          "Store x87 FPU Environment",
		"fstp":            "Store Floating Point Value",
		"fstsw":           "Store x87 FPU Status Word",
		"fsub":            "Subtract",
		"fsubp":           "Subtract and Pop",
		"fsubr":           "Reverse Subtract",
		"fsubrp":          "Reverse Subtract and Pop",
		"ftst":            "Test",
		"fucom":           "Unordered Compare Floating Point Values",
		"fucomi":          "Unordered Compare Floating Point Values and Set EFLAGS",
		"fucomip":         "Unordered Compare Floating Point Values and Set EFLAGS and Pop",
		"fucomp":          "Unordered Compare Floating Point Values and Pop",
		"fucompp":         "Unordered Compare Floating Point Values and Pop twice",
		"fwait":           "Wait",
		"fxam":            "Examine ModR/M",
		"fxch":            "Exchange Register Contents",
		"fxrstor":         "Restore x87 FPU, MMX, XMM, and MXCSR State",
		"fxsave":          "Save x87 FPU, MMX Technology, and SSE State",
		"fxtract":         "Extract Exponent and Significand",
		"fyl2x":           "Compute y ∗ log2x",
		"fyl2xp1":         "Compute y ∗ log2(x +1)",
		"haddpd":          "Packed Double-FP Horizontal Add",
		"haddps":          "Packed Single-FP Horizontal Add",
		"hlt":             "Halt",
		"hsubpd":          "Packed Double-FP Horizontal Subtract",
		"hsubps":          "Packed Single-FP Horizontal Subtract",
		"idiv":            "Signed Divide",
		"imul":            "Signed Multiply",
		"in":              "Input from Port",
		"inc":             "Increment by 1",
		"ins":             "Input from Port to String",
		"insb":            "Input Byte from Port to String",
		"insd":            "Input Double-word from Port to String",
		"insertps":        "Insert Packed Single Precision Floating-Point Value",
		"insw":            "Input Word from Port to String",
		"int":             "Call to Interrupt Procedure",
		"into":            "Overflow Exception (INT 4)",
		"int3":            "Breakpoint Exception (INT 3)",
		"invd":            "Invalidate Internal Caches",
		"invlpg":          "Invalidate TLB Entries",
		"invpcid":         "Invalidate Process-Context Identifier",
		"iret":            "Interrupt Return",
		"iretd":           "Interrupt Return",
		"jmp":             "Jump",
		"j":               "Conditional Jump",
		"lahf":            "Load Status Flags into AH Register",
		"lar":             "Load Access Rights Byte",
		"lddqu":           "Load Unaligned Integer 128 Bits",
		"ldmxcsr":         "Load MXCSR Register",
		"lds":             "Load Far Pointer (with DS)",
		"lea":             "Load Effective Address",
		"leave":           "High Level Procedure Exit",
		"les":             "Load Far Pointer (with ES)",
		"lfence":          "Load Fence",
		"lfs":             "Load Far Pointer (with FS)",
		"lgdt":            "Load Global/Interrupt Descriptor Table Register",
		"lgs":             "Load Far Pointer (with GS)",
		"lidt":            "Load Global/Interrupt Descriptor Table Register",
		"lldt":            "Load Local Descriptor Table Register",
		"lmsw":            "Load Machine Status Word",
		"lock":            "Assert LOCK# Signal Prefix",
		"lods":            "Load String",
		"lodsb":           "Load Byte String",
		"lodsd":           "Load Double-word String",
		"lodsq":           "Load Quad-word String",
		"lodsw":           "Load Word String",
		"loop":            "Loop According to ECX Counter",
		"lsl":             "Load Segment Limit",
		"lss":             "Load Far Pointer (with SS)",
		"ltr":             "Load Task Register",
		"lzcnt":           "Count the Number of Leading Zero Bits",
		"maskmovdqu":      "Store Selected Bytes of Double Quadword",
		"maskmovq":        "Store Selected Bytes of Quadword",
		"maxpd":           "Return Maximum Packed Double-Precision Floating-Point Values",
		"maxps":           "Return Maximum Packed Single-Precision Floating-Point Values",
		"maxsd":           "Return Maximum Scalar Double-Precision Floating-Point Value",
		"maxss":           "Return Maximum Scalar Single-Precision Floating-Point Value",
		"mfence":          "Memory Fence",
		"minpd":           "Return Minimum Packed Double-Precision Floating-Point Values",
		"minps":           "Return Minimum Packed Single-Precision Floating-Point Values",
		"minsd":           "Return Minimum Scalar Double-Precision Floating-Point Value",
		"minss":           "Return Minimum Scalar Single-Precision Floating-Point Value",
		"monitor":         "Set Up Monitor Address",
		"mov":             "Move",
		"movabs":          "Move 64-bit Absolute Value",
		"movapd":          "Move Aligned Packed Double-Precision Floating-Point Values",
		"movaps":          "Move Aligned Packed Single-Precision Floating-Point Values",
		"movbe":           "Move Data After Swapping Bytes",
		"movd":            "Move Doubleword/Move Quadword",
		"movddup":         "Move One Double-FP and Duplicate",
		"movdq2q":         "Move Quadword from XMM to MMX Technology Register",
		"movdqa":          "Move Aligned Double Quadword",
		"movdqu":          "Move Unaligned Double Quadword",
		"movhlps":         "Move Packed Single-Precision Floating-Point Values High to Low",
		"movhpd":          "Move High Packed Double-Precision Floating-Point Value",
		"movhps":          "Move High Packed Single-Precision Floating-Point Values",
		"movlhps":         "Move Packed Single-Precision Floating-Point Values Low to High",
		"movlpd":          "Move Low Packed Double-Precision Floating-Point Value",
		"movlps":          "Move Low Packed Single-Precision Floating-Point Values",
		"movmskpd":        "Extract Packed Double-Precision Floating-Point Sign Mask",
		"movmskps":        "Extract Packed Single-Precision Floating-Point Sign Mask",
		"movntdq":         "Store Double Quadword Using Non-Temporal Hint",
		"movntdqa":        "Load Double Quadword Non-Temporal Aligned Hint",
		"movnti":          "Store Doubleword Using Non-Temporal Hint",
		"movntpd":         "Store Packed Double-Precision Floating-Point Values Using Non-Temporal Hint",
		"movntps":         "Store Packed Single-Precision Floating-Point Values Using Non-Temporal Hint",
		"movntq":          "Store of Quadword Using Non-Temporal Hint",
		"movq":            "Move Doubleword/Move Quadword",
		"movq2dq":         "Move Quadword from MMX Technology to XMM Register",
		"movs":            "Move Data from String to String",
		"movsb":           "Move Data from String to String",
		"movsd":           "Move Data from String to String",
		"movshdup":        "Move Packed Single-FP High and Duplicate",
		"movsldup":        "Move Packed Single-FP Low and Duplicate",
		"movsq":           "Move Data from String to String",
		"movss":           "Move Scalar Single-Precision Floating-Point Values",
		"movsw":           "Move Data from String to String",
		"movsx":           "Move with Sign-Extension",
		"movsxd":          "Move with Sign-Extension",
		"movsbw":          "Move with Sign-Extension: Byte to Word",
		"movsbl":          "Move with Sign-Extension: Byte to Doubleword",
		"movsbq":          "Move with Sign-Extension: Byte to Quadword",
		"movswl":          "Move with Sign-Extension: Word to Doubleword",
		"movswq":          "Move with Sign-Extension: Word to Quadword",
		"movslq":          "Move with Sign-Extension: Doubleword to Quadword",
		"movupd":          "Move Unaligned Packed Double-Precision Floating-Point Values",
		"movups":          "Move Unaligned Packed Single-Precision Floating-Point Values",
		"movzx":           "Move with Zero-Extension",
		"movzbw":          "Move with Zero-Extension: Byte to Word",
		"movzbl":          "Move with Zero-Extension: Byte to Doubleword",
		"movzbq":          "Move with Zero-Extension: Byte to Quadword",
		"movzwl":          "Move with Zero-Extension: Word to Doubleword",
		"movzwq":          "Move with Zero-Extension: Word to Quadword",
		"movzlq":          "Move with Zero-Extension: Doubleword to Quadword",
		"mpsadbw":         "Compute Multiple Packed Sums of Absolute Difference",
		"mul":             "Unsigned Multiply",
		"mulpd":           "Multiply Packed Double-Precision Floating-Point Values",
		"mulps":           "Multiply Packed Single-Precision Floating-Point Values",
		"mulsd":           "Multiply Scalar Double-Precision Floating-Point Values",
		"mulss":           "Multiply Scalar Single-Precision Floating-Point Values",
		"mwait":           "Monitor Wait",
		"mulx":            "Unsigned Multiply Without Affecting Flags",
		"neg":             "Two's Complement Negation",
		"nop":             "No Operation",
		"not":             "One's Complement Negation",
		"or":              "Logical Inclusive OR",
		"orpd":            "Bitwise Logical OR of Double-Precision Floating-Point Values",
		"orps":            "Bitwise Logical OR of Single-Precision Floating-Point Values",
		"out":             "Output to Port",
		"outs":            "Output String to Port",
		"outsb":           "Output Byte String to Port",
		"outsd":           "Output Double-word String to Port",
		"outsw":           "Output Word String to Port",
		"pabsb":           "Packed Absolute Byte Value",
		"pabsd":           "Packed Absolute Double-word Value",
		"pabsw":           "Packed Absolute Word Value",
		"packssdw":        "Pack with Signed Saturation",
		"packsswb":        "Pack with Signed Saturation",
		"packusdw":        "Pack with Unsigned Saturation",
		"packuswb":        "Pack with Unsigned Saturation",
		"paddb":           "Add Packed Integers",
		"paddd":           "Add Packed Integers",
		"paddq":           "Add Packed Quadword Integers",
		"paddsb":          "Add Packed Signed Integers with Signed Saturation",
		"paddsw":          "Add Packed Signed Integers with Signed Saturation",
		"paddusb":         "Add Packed Unsigned Integers with Unsigned Saturation",
		"paddusw":         "Add Packed Unsigned Integers with Unsigned Saturation",
		"paddw":           "Add Packed Integers",
		"palignr":         "Packed Align Right",
		"pand":            "Logical AND",
		"pandn":           "Logical AND NOT",
		"pause":           "Spin Loop Hint",
		"pavgb":           "Average Packed Integers",
		"pavgw":           "Average Packed Integers",
		"pblendvb":        "Variable Blend Packed Bytes",
		"pblendw":         "Blend Packed Words",
		"pclmulqdq":       "Carry-Less Multiplication Quadword",
		"pcmpeqb":         "Compare Packed Data for Equal",
		"pcmpeqd":         "Compare Packed Data for Equal",
		"pcmpeqq":         "Compare Packed Qword Data for Equal",
		"pcmpeqw":         "Compare Packed Data for Equal",
		"pcmpestri":       "Packed Compare Explicit Length Strings, Return Index",
		"pcmpestrm":       "Packed Compare Explicit Length Strings, Return Mask",
		"pcmpgtb":         "Compare Packed Signed Integers for Greater Than",
		"pcmpgtd":         "Compare Packed Signed Integers for Greater Than",
		"pcmpgtq":         "Compare Packed Data for Greater Than",
		"pcmpgtw":         "Compare Packed Signed Integers for Greater Than",
		"pcmpistri":       "Packed Compare Implicit Length Strings, Return Index",
		"pcmpistrm":       "Packed Compare Implicit Length Strings, Return Mask",
		"pdep":            "Parallel Bits Deposit",
		"pext":            "Parallel Bits Extract",
		"pextrb":          "Extract Byte/Dword/Qword",
		"pextrd":          "Extract Byte/Dword/Qword",
		"pextrq":          "Extract Byte/Dword/Qword",
		"pextrw":          "Extract Word",
		"phaddd":          "Packed Horizontal Add",
		"phaddsw":         "Packed Horizontal Add and Saturate",
		"phaddw":          "Packed Horizontal Add",
		"phminposuw":      "Packed Horizontal Word Minimum",
		"phsubd":          "Packed Horizontal Subtract",
		"phsubsw":         "Packed Horizontal Subtract and Saturate",
		"phsubw":          "Packed Horizontal Subtract",
		"pinsrb":          "Insert Byte/Dword/Qword",
		"pinsrd":          "Insert Byte/Dword/Qword",
		"pinsrq":          "Insert Byte/Dword/Qword",
		"pinsrw":          "Insert Word",
		"pmaddubsw":       "Multiply and Add Packed Signed and Unsigned Bytes",
		"pmaddwd":         "Multiply and Add Packed Integers",
		"pmaxsb":          "Maximum of Packed Signed Byte Integers",
		"pmaxsd":          "Maximum of Packed Signed Dword Integers",
		"pmaxsw":          "Maximum of Packed Signed Word Integers",
		"pmaxub":          "Maximum of Packed Unsigned Byte Integers",
		"pmaxud":          "Maximum of Packed Unsigned Dword Integers",
		"pmaxuw":          "Maximum of Packed Word Integers",
		"pminsb":          "Minimum of Packed Signed Byte Integers",
		"pminsd":          "Minimum of Packed Dword Integers",
		"pminsw":          "Minimum of Packed Signed Word Integers",
		"pminub":          "Minimum of Packed Unsigned Byte Integers",
		"pminud":          "Minimum of Packed Dword Integers",
		"pminuw":          "Minimum of Packed Word Integers",
		"pmovmskb":        "Move Byte Mask",
		"pmovsx":          "Packed Move with Sign Extend",
		"pmovzx":          "Packed Move with Zero Extend",
		"pmuldq":          "Multiply Packed Signed Dword Integers",
		"pmulhrsw":        "Packed Multiply High with Round and Scale",
		"pmulhuw":         "Multiply Packed Unsigned Integers and Store High Result",
		"pmulhw":          "Multiply Packed Signed Integers and Store High Result",
		"pmulld":          "Multiply Packed Signed Dword Integers and Store Low Result",
		"pmullw":          "Multiply Packed Signed Integers and Store Low Result",
		"pmuludq":         "Multiply Packed Unsigned Doubleword Integers",
		"pop":             "Pop a Value from the Stack",
		"popa":            "Pop All General-Purpose Registers",
		"popad":           "Pop All General-Purpose Registers",
		"popcnt":          "Return the Count of Number of Bits Set to 1",
		"popf":            "Pop Stack into EFLAGS Register",
		"popfd":           "Pop Stack into EFLAGS Register",
		"popfq":           "Pop Stack into EFLAGS Register",
		"por":             "Bitwise Logical OR",
		"prefetchw":       "Prefetch Data into Caches in Anticipation of a Write",
		"prefetchwt1":     "Prefetch Vector Data Into Caches with Intent to Write and T1 Hint",
		"prefetch":        "Prefetch Data Into Caches",
		"psadbw":          "Compute Sum of Absolute Differences",
		"pshufb":          "Packed Shuffle Bytes",
		"pshufd":          "Shuffle Packed Doublewords",
		"pshufhw":         "Shuffle Packed High Words",
		"pshuflw":         "Shuffle Packed Low Words",
		"pshufw":          "Shuffle Packed Words",
		"psignb":          "Packed SIGN",
		"psignd":          "Packed SIGN",
		"psignw":          "Packed SIGN",
		"pslld":           "Shift Packed Data Left Logical",
		"pslldq":          "Shift Double Quadword Left Logical",
		"psllq":           "Shift Packed Data Left Logical",
		"psllw":           "Shift Packed Data Left Logical",
		"psrad":           "Shift Packed Data Right Arithmetic",
		"psraw":           "Shift Packed Data Right Arithmetic",
		"psrld":           "Shift Packed Data Right Logical",
		"psrldq":          "Shift Double Quadword Right Logical",
		"psrlq":           "Shift Packed Data Right Logical",
		"psrlw":           "Shift Packed Data Right Logical",
		"psubb":           "Subtract Packed Integers",
		"psubd":           "Subtract Packed Integers",
		"psubq":           "Subtract Packed Quadword Integers",
		"psubsb":          "Subtract Packed Signed Integers with Signed Saturation",
		"psubsw":          "Subtract Packed Signed Integers with Signed Saturation",
		"psubusb":         "Subtract Packed Unsigned Integers with Unsigned Saturation",
		"psubusw":         "Subtract Packed Unsigned Integers with Unsigned Saturation",
		"psubw":           "Subtract Packed Integers",
		"ptest":           "Logical Compare",
		"punpckhbw":       "Unpack High Data",
		"punpckhdq":       "Unpack High Data",
		"punpckhqdq":      "Unpack High Data",
		"punpckhwd":       "Unpack High Data",
		"punpcklbw":       "Unpack Low Data",
		"punpckldq":       "Unpack Low Data",
		"punpcklqdq":      "Unpack Low Data",
		"punpcklwd":       "Unpack Low Data",
		"push":            "Push Word, Doubleword or Quadword Onto the Stack",
		"pusha":           "Push All General-Purpose Registers",
		"pushad":          "Push All General-Purpose Registers",
		"pushf":           "Push EFLAGS Register onto the Stack",
		"pushfd":          "Push EFLAGS Register onto the Stack",
		"pxor":            "Logical Exclusive OR",
		"rcl":             "Rotate Left",
		"rcpps":           "Compute Reciprocals of Packed Single-Precision Floating-Point Values",
		"rcpss":           "Compute Reciprocal of Scalar Single-Precision Floating-Point Values",
		"rcr":             "Rotate Right",
		"rdfsbase":        "Read FS/GS Segment Base",
		"rdgsbase":        "Read FS/GS Segment Base",
		"rdmsr":           "Read from Model Specific Register",
		"rdpmc":           "Read Performance-Monitoring Counters",
		"rdrand":          "Read Random Number",
		"rdseed":          "Read Random SEED",
		"rdtsc":           "Read Time-Stamp Counter",
		"rdtscp":          "Read Time-Stamp Counter and Processor ID",
		"rep":             "Repeat String Operation Prefix",
		"repe":            "Repeat String Operation Prefix",
		"repne":           "Repeat String Operation Prefix",
		"repnz":           "Repeat String Operation Prefix",
		"repz":            "Repeat String Operation Prefix",
		"ret":             "Return from Procedure",
		"rol":             "Rotate Left",
		"ror":             "Rotate Right",
		"rorx":            "Rotate Right Logical Without Affecting Flags",
		"roundpd":         "Round Packed Double Precision Floating-Point Values",
		"roundps":         "Round Packed Single Precision Floating-Point Values",
		"roundsd":         "Round Scalar Double Precision Floating-Point Values",
		"roundss":         "Round Scalar Single Precision Floating-Point Values",
		"rsm":             "Resume from System Management Mode",
		"rsqrtps":         "Compute Reciprocals of Square Roots of Packed Single-Precision Floating-Point Values",
		"rsqrtss":         "Compute Reciprocal of Square Root of Scalar Single-Precision Floating-Point Value",
		"sahf":            "Store AH into Flags",
		"sal":             "Shift Arithmetic Left",
		"sar":             "Shift Arithmetic Right",
		"sarx":            "Shift Without Affecting Flags",
		"sbb":             "Integer Subtraction with Borrow",
		"scas":            "Scan String",
		"scasb":           "Scan Byte String",
		"scasd":           "Scan Double-word String",
		"scasw":           "Scan Word String",
		"set":             "Set Byte on Condition",
		"sfence":          "Store Fence",
		"sgdt":            "Store Global Descriptor Table Register",
		"shl":             "Shift Logical Left",
		"shld":            "Double Precision Shift Left",
		"shlx":            "Shift Without Affecting Flags",
		"shr":             "Shift Logical Right",
		"shrd":            "Double Precision Shift Right",
		"shrx":            "Shift Without Affecting Flags",
		"shufpd":          "Shuffle Packed Double-Precision Floating-Point Values",
		"shufps":          "Shuffle Packed Single-Precision Floating-Point Values",
		"sidt":            "Store Interrupt Descriptor Table Register",
		"sldt":            "Store Local Descriptor Table Register",
		"smsw":            "Store Machine Status Word",
		"sqrtpd":          "Compute Square Roots of Packed Double-Precision Floating-Point Values",
		"sqrtps":          "Compute Square Roots of Packed Single-Precision Floating-Point Values",
		"sqrtsd":          "Compute Square Root of Scalar Double-Precision Floating-Point Value",
		"sqrtss":          "Compute Square Root of Scalar Single-Precision Floating-Point Value",
		"stac":            "Set AC Flag in EFLAGS Register",
		"stc":             "Set Carry Flag",
		"std":             "Set Direction Flag",
		"sti":             "Set Interrupt Flag",
		"stmxcsr":         "Store MXCSR Register State",
		"stos":            "Store String",
		"stosb":           "Store Byte String",
		"stosd":           "Store Double-word String",
		"stosq":           "Store Quad-word String",
		"stosw":           "Store Word String",
		"str":             "Store Task Register",
		"sub":             "Subtract",
		"subpd":           "Subtract Packed Double-Precision Floating-Point Values",
		"subps":           "Subtract Packed Single-Precision Floating-Point Values",
		"subsd":           "Subtract Scalar Double-Precision Floating-Point Values",
		"subss":           "Subtract Scalar Single-Precision Floating-Point Values",
		"swapgs":          "Swap GS Base Register",
		"syscall":         "Fast System Call",
		"sysenter":        "Fast System Call",
		"sysexit":         "Fast Return from Fast System Call",
		"sysret":          "Return From Fast System Call",
		"test":            "Logical Compare",
		"tzcnt":           "Count the Number of Trailing Zero Bits",
		"ucomisd":         "Unordered Compare Scalar Double-Precision Floating-Point Values and Set EFLAGS",
		"ucomiss":         "Unordered Compare Scalar Single-Precision Floating-Point Values and Set EFLAGS",
		"ud2":             "Undefined Instruction",
		"unpckhpd":        "Unpack and Interleave High Packed Double-Precision Floating-Point Values",
		"unpckhps":        "Unpack and Interleave High Packed Single-Precision Floating-Point Values",
		"unpcklpd":        "Unpack and Interleave Low Packed Double-Precision Floating-Point Values",
		"unpcklps":        "Unpack and Interleave Low Packed Single-Precision Floating-Point Values",
		"vbroadcast":      "Broadcast Floating-Point Data",
		"vcvtph2ps":       "Convert 16-bit FP Values to Single-Precision FP Values",
		"vcvtps2ph":       "Convert Single-Precision FP value to 16-bit FP value",
		"verr":            "Verify a Segment for Reading or Writing",
		"verw":            "Verify a Segment for Reading or Writing",
		"vextractf128":    "Extract Packed Floating-Point Values",
		"vextracti128":    "Extract packed Integer Values",
		"vfmadd132pd":     "Fused Multiply-Add of Packed Double-Precision Floating-Point Values",
		"vfmadd132ps":     "Fused Multiply-Add of Packed Single-Precision Floating-Point Values",
		"vfmadd132sd":     "Fused Multiply-Add of Scalar Double-Precision Floating-Point Values",
		"vfmadd132ss":     "Fused Multiply-Add of Scalar Single-Precision Floating-Point Values",
		"vfmadd213pd":     "Fused Multiply-Add of Packed Double-Precision Floating-Point Values",
		"vfmadd213ps":     "Fused Multiply-Add of Packed Single-Precision Floating-Point Values",
		"vfmadd213sd":     "Fused Multiply-Add of Scalar Double-Precision Floating-Point Values",
		"vfmadd213ss":     "Fused Multiply-Add of Scalar Single-Precision Floating-Point Values",
		"vfmadd231pd":     "Fused Multiply-Add of Packed Double-Precision Floating-Point Values",
		"vfmadd231ps":     "Fused Multiply-Add of Packed Single-Precision Floating-Point Values",
		"vfmadd231sd":     "Fused Multiply-Add of Scalar Double-Precision Floating-Point Values",
		"vfmadd231ss":     "Fused Multiply-Add of Scalar Single-Precision Floating-Point Values",
		"vfmaddsub132pd":  "Fused Multiply-Alternating Add/Subtract of Packed Double-Precision Floating-Point Values",
		"vfmaddsub132ps":  "Fused Multiply-Alternating Add/Subtract of Packed Single-Precision Floating-Point Values",
		"vfmaddsub213pd":  "Fused Multiply-Alternating Add/Subtract of Packed Double-Precision Floating-Point Values",
		"vfmaddsub213ps":  "Fused Multiply-Alternating Add/Subtract of Packed Single-Precision Floating-Point Values",
		"vfmaddsub231pd":  "Fused Multiply-Alternating Add/Subtract of Packed Double-Precision Floating-Point Values",
		"vfmaddsub231ps":  "Fused Multiply-Alternating Add/Subtract of Packed Single-Precision Floating-Point Values",
		"vfmsub132pd":     "Fused Multiply-Subtract of Packed Double-Precision Floating-Point Values",
		"vfmsub132ps":     "Fused Multiply-Subtract of Packed Single-Precision Floating-Point Values",
		"vfmsub132sd":     "Fused Multiply-Subtract of Scalar Double-Precision Floating-Point Values",
		"vfmsub132ss":     "Fused Multiply-Subtract of Scalar Single-Precision Floating-Point Values",
		"vfmsub213pd":     "Fused Multiply-Subtract of Packed Double-Precision Floating-Point Values",
		"vfmsub213ps":     "Fused Multiply-Subtract of Packed Single-Precision Floating-Point Values",
		"vfmsub213sd":     "Fused Multiply-Subtract of Scalar Double-Precision Floating-Point Values",
		"vfmsub213ss":     "Fused Multiply-Subtract of Scalar Single-Precision Floating-Point Values",
		"vfmsub231pd":     "Fused Multiply-Subtract of Packed Double-Precision Floating-Point Values",
		"vfmsub231ps":     "Fused Multiply-Subtract of Packed Single-Precision Floating-Point Values",
		"vfmsub231sd":     "Fused Multiply-Subtract of Scalar Double-Precision Floating-Point Values",
		"vfmsub231ss":     "Fused Multiply-Subtract of Scalar Single-Precision Floating-Point Values",
		"vfmsubadd132pd":  "Fused Multiply-Alternating Subtract/Add of Packed Double-Precision Floating-Point Values",
		"vfmsubadd132ps":  "Fused Multiply-Alternating Subtract/Add of Packed Single-Precision Floating-Point Values",
		"vfmsubadd213pd":  "Fused Multiply-Alternating Subtract/Add of Packed Double-Precision Floating-Point Values",
		"vfmsubadd213ps":  "Fused Multiply-Alternating Subtract/Add of Packed Single-Precision Floating-Point Values",
		"vfmsubadd231pd":  "Fused Multiply-Alternating Subtract/Add of Packed Double-Precision Floating-Point Values",
		"vfmsubadd231ps":  "Fused Multiply-Alternating Subtract/Add of Packed Single-Precision Floating-Point Values",
		"vfnmadd132pd":    "Fused Negative Multiply-Add of Packed Double-Precision Floating-Point Values",
		"vfnmadd132ps":    "Fused Negative Multiply-Add of Packed Single-Precision Floating-Point Values",
		"vfnmadd132sd":    "Fused Negative Multiply-Add of Scalar Double-Precision Floating-Point Values",
		"vfnmadd132ss":    "Fused Negative Multiply-Add of Scalar Single-Precision Floating-Point Values",
		"vfnmadd213pd":    "Fused Negative Multiply-Add of Packed Double-Precision Floating-Point Values",
		"vfnmadd213ps":    "Fused Negative Multiply-Add of Packed Single-Precision Floating-Point Values",
		"vfnmadd213sd":    "Fused Negative Multiply-Add of Scalar Double-Precision Floating-Point Values",
		"vfnmadd213ss":    "Fused Negative Multiply-Add of Scalar Single-Precision Floating-Point Values",
		"vfnmadd231pd":    "Fused Negative Multiply-Add of Packed Double-Precision Floating-Point Values",
		"vfnmadd231ps":    "Fused Negative Multiply-Add of Packed Single-Precision Floating-Point Values",
		"vfnmadd231sd":    "Fused Negative Multiply-Add of Scalar Double-Precision Floating-Point Values",
		"vfnmadd231ss":    "Fused Negative Multiply-Add of Scalar Single-Precision Floating-Point Values",
		"vfnmsub132pd":    "Fused Negative Multiply-Subtract of Packed Double-Precision Floating-Point Values",
		"vfnmsub132ps":    "Fused Negative Multiply-Subtract of Packed Single-Precision Floating-Point Values",
		"vfnmsub132sd":    "Fused Negative Multiply-Subtract of Scalar Double-Precision Floating-Point Values",
		"vfnmsub132ss":    "Fused Negative Multiply-Subtract of Scalar Single-Precision Floating-Point Values",
		"vfnmsub213pd":    "Fused Negative Multiply-Subtract of Packed Double-Precision Floating-Point Values",
		"vfnmsub213ps":    "Fused Negative Multiply-Subtract of Packed Single-Precision Floating-Point Values",
		"vfnmsub213sd":    "Fused Negative Multiply-Subtract of Scalar Double-Precision Floating-Point Values",
		"vfnmsub213ss":    "Fused Negative Multiply-Subtract of Scalar Single-Precision Floating-Point Values",
		"vfnmsub231pd":    "Fused Negative Multiply-Subtract of Packed Double-Precision Floating-Point Values",
		"vfnmsub231ps":    "Fused Negative Multiply-Subtract of Packed Single-Precision Floating-Point Values",
		"vfnmsub231sd":    "Fused Negative Multiply-Subtract of Scalar Double-Precision Floating-Point Values",
		"vfnmsub231ss":    "Fused Negative Multiply-Subtract of Scalar Single-Precision Floating-Point Values",
		"vgatherdpd":      "Gather Packed DP FP Values Using Signed Dword/Qword Indices",
		"vgatherdps":      "Gather Packed SP FP values Using Signed Dword/Qword Indices",
		"vgatherqpd":      "Gather Packed DP FP Values Using Signed Dword/Qword Indices",
		"vgatherqps":      "Gather Packed SP FP values Using Signed Dword/Qword Indices",
		"vinsertf128":     "Insert Packed Floating-Point Values",
		"vinserti128":     "Insert Packed Integer Values",
		"vmaskmov":        "Conditional SIMD Packed Loads and Stores",
		"vpblendd":        "Blend Packed Dwords",
		"vpbroadcast":     "Broadcast Integer Data",
		"vperm2f128":      "Permute Floating-Point Values",
		"vperm2i128":      "Permute Integer Values",
		"vpermd":          "Full Doublewords Element Permutation",
		"vpermilpd":       "Permute Double-Precision Floating-Point Values",
		"vpermilps":       "Permute Single-Precision Floating-Point Values",
		"vpermpd":         "Permute Double-Precision Floating-Point Elements",
		"vpermps":         "Permute Single-Precision Floating-Point Elements",
		"vpermq":          "Qwords Element Permutation",
		"vpgatherdd":      "Gather Packed Dword Values Using Signed Dword/Qword Indices",
		"vpgatherdq":      "Gather Packed Qword Values Using Signed Dword/Qword Indices",
		"vpgatherqd":      "Gather Packed Dword Values Using Signed Dword/Qword Indices",
		"vpgatherqq":      "Gather Packed Qword Values Using Signed Dword/Qword Indices",
		"vpmaskmov":       "Conditional SIMD Integer Packed Loads and Stores",
		"vpsllvd":         "Variable Bit Shift Left Logical",
		"vpsllvq":         "Variable Bit Shift Left Logical",
		"vpsravd":         "Variable Bit Shift Right Arithmetic",
		"vpsrlvd":         "Variable Bit Shift Right Logical",
		"vpsrlvq":         "Variable Bit Shift Right Logical",
		"vtestpd":         "Packed Bit Test",
		"vtestps":         "Packed Bit Test",
		"vzeroall":        "Zero All YMM Registers",
		"vzeroupper":      "Zero Upper Bits of YMM Registers",
		"wait":            "Wait",
		"wbinvd":          "Write Back and Invalidate Cache",
		"wrfsbase":        "Write FS/GS Segment Base",
		"wrgsbase":        "Write FS/GS Segment Base",
		"wrmsr":           "Write to Model Specific Register",
		"xabort":          "Transactional Abort",
		"xacquire":        "Hardware Lock Elision Prefix Hints",
		"xadd":            "Exchange and Add",
		"xbegin":          "Transactional Begin",
		"xchg":            "Exchange Register/Memory with Register",
		"xend":            "Transactional End",
		"xgetbv":          "Get Value of Extended Control Register",
		"xlat":            "Table Look-up Translation",
		"xlatb":           "Table Look-up Translation",
		"xor":             "Logical Exclusive OR",
		"xorpd":           "Bitwise Logical XOR for Double-Precision Floating-Point Values",
		"xorps":           "Bitwise Logical XOR for Single-Precision Floating-Point Values",
		"xrelease":        "Hardware Lock Elision Prefix Hints",
		"xrstor":          "Restore Processor Extended States",
		"xrstors":         "Restore Processor Extended States Supervisor",
		"xsave":           "Save Processor Extended States",
		"xsavec":          "Save Processor Extended States with Compaction",
		"xsaveopt":        "Save Processor Extended States Optimized",
		"xsaves":          "Save Processor Extended States Supervisor",
		"xsetbv":          "Set Extended Control Register",
		"xtest":           "Test If In Transactional Execution",
	}

	Cond_x86_64 = map[string]string{
		"g":    "Greater",
		"ng":   "Not Greater",
		"ge":   "Greater or Equal",
		"nge":  "Not Greater or Equal",
		"l":    "Less",
		"nl":   "Not Less",
		"le":   "Less or Equal",
		"nle":  "Not Less or Equal",
		"a":    "Above",
		"na":   "Not Above",
		"ae":   "Above or Equal",
		"nae":  "Not Above or Equal",
		"b":    "Below",
		"nb":   "Not Below",
		"be":   "Below or Equal",
		"nbe":  "Not Below or Equal",
		"o":    "Overflow",
		"no":   "Not Overflow",
		"p":    "Parity",
		"np":   "Not Parity",
		"pe":   "Parity Even",
		"po":   "Parity Odd",
		"e":    "Equal",
		"ne":   "Not Equal",
		"s":    "Sign",
		"ns":   "Not Sign",
		"z":    "Zero",
		"nz":   "Not Zero",
		"cxz":  "CX register is Zero",
		"excz": "ECX register is Zero",
	}

	CondInsn_x86_64 = []string{"cmov", "j", "loop", "set"}
}
